### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by sploosh-was-taken** [3kh0/echodev-pylon#1]
Hello 3kh0,

I'm known as _Vantablack_ or _3kh0 but suit_ on your discord server. I was wondering if I could help you with some projects this summer. I would also like to join your organizations: **Repo Repairs**, **Blooketware**, and **Pylon Apps**.

Thanks,
Vantablack

**Comment by 3kh0** [comment]
@sploosh-was-taken Please DM me on discord for these kinds of questions. Thank you.

**Comment by sploosh-was-taken** [comment]
> @sploosh-was-taken Please DM me on discord for these kinds of questions. Thank you.

@3kh0 I can't access discord right now because it has been blocked on all my devices. Maybe you could text or email me instead? (Use my official email in my profile please)
